name: Build and Deploy Blender Extensions (organized by ID/version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Init and update submodules (pull latest from remote)
        run: |
          git submodule init
          git submodule update --remote --recursive

      - name: Set up Blender Portable (Linux版 4.4RC)
        run: |
          mkdir blender
          curl -L https://mirror.freedif.org/blender/release/Blender4.4/blender-4.4.1-linux-x64.tar.xz | tar xJ -C blender --strip-components=1

      - name: Create public directory
        run: mkdir public

      - name: Build each extension with Blender (extension build)
        run: |
          for dir in extensions/*; do
            if [ -d "$dir" ]; then
              ./blender/blender --background --command extension build --repo-dir "$dir" --output-dir ./build_temp
            fi
          done

      - name: Organize built artifacts by ID and Version
        run: |
          mkdir -p public
          for zip in build_temp/*.zip; do
            # 例: save_versions_redirector-1.1.0.zip
            filename=$(basename "$zip")
            name_version="${filename%.zip}"  # 拡張子除去
            id=$(echo "$name_version" | sed 's/-[0-9]\+\.[0-9]\+\.[0-9]\+$//')
            version=$(echo "$name_version" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
            
            # ディレクトリ作成
            mkdir -p "public/$id/$version"
            mkdir -p "public/$id/latest"

            # zipを配置
            cp "$zip" "public/$id/$version/${id}-${version}.zip"
            cp "$zip" "public/$id/latest/${id}-latest.zip"

            # 署名ファイル生成
            sha256sum "public/$id/$version/${id}-${version}.zip" | awk '{print $1}' > "public/$id/$version/${id}-${version}.zip.sig"
            sha256sum "public/$id/latest/${id}-latest.zip" | awk '{print $1}' > "public/$id/latest/${id}-latest.zip.sig"
          done

      - name: Deploy public directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
